// ── IMAGE MAP ───────────────────────────────────────────────────────────────
export const IMG = {
  brake_pads:  'brake_pads.jpg',
  brake_rotor: 'brake_rotor.jpg',
  brake_cal:   'brake_caliper.jpg',
  spark:       'spark_plug_iridium.jpg',
  head_gasket: 'engine_head_gasket.jpg',
  water_pump:  'water_pump.jpg',
  shock:       'shock_absorber_kyb.jpg',
  coil:        'coil_spring.jpg',
  oil_filter:  'oil_filter_product.jpg',
  air_filter:  'air_filter_performance.jpg',
  led_head:    'led_headlight.jpg',
  helmet:      'bike_helmet.jpg',
  gloves:      'bike_gloves.jpg',
  chain_lube:  'bike_chain_lube.jpg',
  dashcam:     'car_dashcam.jpg',
  seat_cover:  'car_seat_cover.jpg',
  car_perfume: 'car_perfume.jpg',
  fog:         'car_fog_lamp_product_1778330994691.jpg',
  elec:        'car_electricals_category_1778327286059.jpg',
  ac_comp:     'car_ac_compressor_product_1778330845400.jpg',
  cv_axle:     'car_cv_axle_product_1778330921969.jpg',
  timing:      'car_timing_belt_product_1778330941180.jpg',
  body:        'car_body_parts_category_1778327203501.jpg',
  exhaust:     'car_exhaust_muffler_product_1778330861870.jpg',
  wiper:       'car_wiper_blades_product_1778327371060.jpg',
  battery:     'car_battery_product_1778327386793.jpg',
  clutch:      'car_clutch_kit_product_1778327402731.jpg',
  wheel:       'car_alloy_wheel_product_1778327419390.jpg',
  rotor:       'car_disc_rotor_product_1778330979465.jpg',
  steering:    'car_steering_pump_product_1778330881007.jpg',
  radiator:    'car_radiator_product_1778330830798.jpg',
  fuel_pump:   'car_fuel_pump_product_1778330903755.jpg',
  susp:        'car_suspension_category_1778327219701.jpg',
  filter_cat:  'car_filters_category_1778327237229.jpg',
  trans:       'car_transmission_category_1778327271267.jpg',
};

export const CATEGORIES = [
  { id:'brake',     name:'Brake System',    icon:'🔴', img: IMG.brake_pads,   desc:'Pads, rotors, calipers' },
  { id:'engine',    name:'Engine Parts',    icon:'⚙️', img: IMG.spark,        desc:'Plugs, gaskets, pumps' },
  { id:'susp',      name:'Suspension',      icon:'🔧', img: IMG.shock,        desc:'Shocks, springs, arms' },
  { id:'filter',    name:'Filters',         icon:'🌀', img: IMG.oil_filter,   desc:'Oil, air, fuel, cabin' },
  { id:'light',     name:'Lighting',        icon:'💡', img: IMG.led_head,     desc:'LED, HID, halogen' },
  { id:'elec',      name:'Electricals',     icon:'⚡', img: IMG.elec,         desc:'Alternator, sensors' },
  { id:'trans',     name:'Transmission',    icon:'🔩', img: IMG.cv_axle,      desc:'Gearbox, CV axle, clutch' },
  { id:'body',      name:'Body Parts',      icon:'🚗', img: IMG.body,         desc:'Bumpers, mirrors, grille' },
  { id:'wiper',     name:'Wiper Blades',    icon:'🌧️', img: IMG.wiper,        desc:'Flat, hybrid, rear' },
  { id:'battery',   name:'Batteries',       icon:'🔋', img: IMG.battery,      desc:'12V, AGM, deep cycle' },
  { id:'clutch',    name:'Clutch Kit',      icon:'🎯', img: IMG.clutch,       desc:'Plate, pressure, bearing' },
  { id:'wheel',     name:'Alloy Wheels',    icon:'🏎️', img: IMG.wheel,        desc:'14", 15", 16", 17"' },
  { id:'bike_gear', name:'Bike Gear',       icon:'🏍️', img: IMG.helmet,       desc:'Helmets, gloves, jackets' },
  { id:'bike_care', name:'Bike Care',       icon:'🛢️', img: IMG.chain_lube,   desc:'Chain lube, oils, polish' },
  { id:'car_acc',   name:'Car Accessories', icon:'✨', img: IMG.dashcam,      desc:'Dashcam, seat covers, mats' },
];

export const PRODUCTS = [
  { id:'p_brake_1', cat:'brake', name:'Brembo Front Brake Pad Set', partNo:'PT-BRAKE-4704', brand:'Brembo', price:5209, mrp:6018, img:'p_brake_1.jpg', type:'Genuine', fitment:'Hyundai i20 / i10', rating:4.4, reviews:527, stock:true, badge:'Best Seller' },
  { id:'p_brake_2', cat:'brake', name:'Bosch Rear Drum Brake Shoe', partNo:'PT-BRAKE-1794', brand:'Bosch', price:5074, mrp:7547, img:'p_brake_2.webp', type:'Aftermarket', fitment:'Maruti Alto / WagonR', rating:5.0, reviews:245, stock:true, badge:'New' },
  { id:'p_brake_3', cat:'brake', name:'TVS Vented Disc Brake Rotor', partNo:'PT-BRAKE-5973', brand:'TVS', price:6712, mrp:7216, img:'p_brake_3.webp', type:'Genuine', fitment:'Honda City / Civic', rating:4.2, reviews:351, stock:true, badge:'' },
  { id:'p_brake_4', cat:'brake', name:'ATE Brake Caliper Assembly', partNo:'PT-BRAKE-4577', brand:'ATE', price:4761, mrp:6934, img:'p_brake_4.png', type:'Aftermarket', fitment:'Toyota Innova Crysta', rating:4.7, reviews:491, stock:true, badge:'' },
  { id:'p_brake_5', cat:'brake', name:'TRW Ceramic Performance Pads', partNo:'PT-BRAKE-9335', brand:'TRW', price:1095, mrp:2575, img:'p_brake_5.webp', type:'Genuine', fitment:'Kia Seltos / Sonet', rating:4.6, reviews:587, stock:true, badge:'Premium' },
  { id:'p_brake_6', cat:'brake', name:'EBC Brake Master Cylinder', partNo:'PT-BRAKE-4186', brand:'EBC', price:1088, mrp:2739, img:'p_brake_6.png', type:'Aftermarket', fitment:'Tata Nexon / Altroz', rating:4.7, reviews:96, stock:true, badge:'' },
  { id:'p_brake_7', cat:'brake', name:'Akebono Brake Fluid DOT 4 (1L)', partNo:'PT-BRAKE-6649', brand:'Akebono', price:3629, mrp:3933, img:'p_brake_7.jpg', type:'Genuine', fitment:'Mahindra XUV300', rating:4.2, reviews:245, stock:true, badge:'Best Seller' },
  { id:'p_brake_8', cat:'brake', name:'Wagner Stainless Brake Line Kit', partNo:'PT-BRAKE-8488', brand:'Wagner', price:2301, mrp:4238, img:'p_brake_8.jpg', type:'Aftermarket', fitment:'VW Polo / Vento', rating:4.5, reviews:304, stock:true, badge:'New' },
  { id:'p_brake_9', cat:'brake', name:'Nissin Performance Slotted Rotors', partNo:'PT-BRAKE-4556', brand:'Nissin', price:1019, mrp:1423, img:'p_brake_9.png', type:'Genuine', fitment:'Maruti Swift / Dzire', rating:4.2, reviews:439, stock:true, badge:'' },
  { id:'p_brake_10', cat:'brake', name:'Endless Drum Brake Hardware Kit', partNo:'PT-BRAKE-8712', brand:'Endless', price:4580, mrp:4863, img:'p_brake_10.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.9, reviews:241, stock:true, badge:'Hot' },
  { id:'p_engine_11', cat:'engine', name:'NGK Iridium Spark Plug (x4)', partNo:'PT-ENGINE-5396', brand:'NGK', price:6608, mrp:8774, img:'p_engine_11.jpg', type:'Genuine', fitment:'Universal Petrol', rating:4.5, reviews:486, stock:true, badge:'Best Seller' },
  { id:'p_engine_12', cat:'engine', name:'Denso Cylinder Head Gasket Set', partNo:'PT-ENGINE-1352', brand:'Denso', price:7285, mrp:8997, img:'p_engine_12.jpg', type:'Aftermarket', fitment:'Maruti Swift / Baleno 1.2L', rating:4.8, reviews:133, stock:true, badge:'New' },
  { id:'p_engine_13', cat:'engine', name:'Bosch Water Pump Assembly', partNo:'PT-ENGINE-3490', brand:'Bosch', price:7015, mrp:7861, img:'p_engine_13.jpg', type:'Genuine', fitment:'Hyundai Creta 1.5P', rating:4.4, reviews:176, stock:true, badge:'' },
  { id:'p_engine_14', cat:'engine', name:'Mahle Timing Chain Kit', partNo:'PT-ENGINE-4528', brand:'Mahle', price:721, mrp:2492, img:'p_engine_14.jpg', type:'Aftermarket', fitment:'Ford EcoSport / Fiesta', rating:4.9, reviews:362, stock:true, badge:'' },
  { id:'p_engine_15', cat:'engine', name:'Elring Piston Ring Set (x4)', partNo:'PT-ENGINE-3927', brand:'Elring', price:1512, mrp:3056, img:'p_engine_15.webp', type:'Genuine', fitment:'Tata Nexon / Altroz', rating:4.5, reviews:445, stock:true, badge:'Premium' },
  { id:'p_engine_16', cat:'engine', name:'Victor Reinz Valve Cover Gasket', partNo:'PT-ENGINE-1514', brand:'Victor Reinz', price:5835, mrp:7377, img:'p_engine_16.jpg', type:'Aftermarket', fitment:'Renault Duster / Kwid', rating:4.9, reviews:239, stock:true, badge:'' },
  { id:'p_engine_17', cat:'engine', name:'Gates Oil Pump Assembly', partNo:'PT-ENGINE-7753', brand:'Gates', price:5244, mrp:5515, img:'p_engine_17.jpg', type:'Genuine', fitment:'Honda Jazz / WR-V', rating:4.9, reviews:285, stock:true, badge:'Best Seller' },
  { id:'p_engine_18', cat:'engine', name:'Continental Crankshaft Pulley', partNo:'PT-ENGINE-9865', brand:'Continental', price:3531, mrp:4233, img:'p_engine_18.jpg', type:'Aftermarket', fitment:'VW Polo / Vento 1.0TSI', rating:4.7, reviews:279, stock:true, badge:'New' },
  { id:'p_engine_19', cat:'engine', name:'Dayco Camshaft Position Sensor', partNo:'PT-ENGINE-3773', brand:'Dayco', price:7027, mrp:7520, img:'p_engine_19.jpg', type:'Genuine', fitment:'Toyota Fortuner 2.7', rating:4.9, reviews:571, stock:true, badge:'' },
  { id:'p_engine_20', cat:'engine', name:'SKF Engine Mount Bracket', partNo:'PT-ENGINE-9493', brand:'SKF', price:4442, mrp:6653, img:'p_engine_20.jpg', type:'Aftermarket', fitment:'Maruti Ertiga / S-Cross', rating:4.6, reviews:367, stock:true, badge:'Hot' },
  { id:'p_susp_21', cat:'susp', name:'Gabriel Front Shock Absorber', partNo:'PT-SUSP-5378', brand:'Gabriel', price:4760, mrp:6285, img:'p_susp_21.webp', type:'Genuine', fitment:'Maruti Ertiga / S-Cross', rating:4.6, reviews:285, stock:true, badge:'Best Seller' },
  { id:'p_susp_22', cat:'susp', name:'Monroe Lower Ball Joint', partNo:'PT-SUSP-9000', brand:'Monroe', price:3328, mrp:5746, img:'p_susp_22.webp', type:'Aftermarket', fitment:'Honda Jazz / WR-V', rating:4.9, reviews:463, stock:true, badge:'New' },
  { id:'p_susp_23', cat:'susp', name:'KYB Stabilizer Sway Bar Link', partNo:'PT-SUSP-3263', brand:'KYB', price:4841, mrp:7032, img:'p_susp_23.jpg', type:'Genuine', fitment:'VW Polo / Vento', rating:5.0, reviews:315, stock:true, badge:'' },
  { id:'p_susp_24', cat:'susp', name:'Bilstein Complete Strut Assembly', partNo:'PT-SUSP-2377', brand:'Bilstein', price:2420, mrp:2803, img:'p_susp_24.webp', type:'Aftermarket', fitment:'Hyundai Creta / Venue', rating:4.5, reviews:235, stock:true, badge:'' },
  { id:'p_susp_25', cat:'susp', name:'Ohlins Lower Control Arm', partNo:'PT-SUSP-4327', brand:'Ohlins', price:855, mrp:2750, img:'p_susp_25.jpg', type:'Genuine', fitment:'Toyota Fortuner / SW4', rating:4.2, reviews:228, stock:true, badge:'Premium' },
  { id:'p_susp_26', cat:'susp', name:'Koni Coil Spring Set (Pair)', partNo:'PT-SUSP-5318', brand:'Koni', price:3181, mrp:3337, img:'p_susp_26.jpg', type:'Aftermarket', fitment:'Tata Harrier / Safari', rating:4.7, reviews:293, stock:true, badge:'' },
  { id:'p_susp_27', cat:'susp', name:'Moog Inner Tie Rod End', partNo:'PT-SUSP-2131', brand:'Moog', price:2163, mrp:2427, img:'p_susp_27.jpg', type:'Genuine', fitment:'Kia Seltos / Sonet', rating:4.7, reviews:378, stock:true, badge:'Best Seller' },
  { id:'p_susp_28', cat:'susp', name:'Lemforder Front Wheel Bearing Hub', partNo:'PT-SUSP-9833', brand:'Lemforder', price:5315, mrp:6451, img:'p_susp_28.webp', type:'Aftermarket', fitment:'Maruti Brezza / Ciaz', rating:4.1, reviews:548, stock:true, badge:'New' },
  { id:'p_susp_29', cat:'susp', name:'TRW Suspension Bushing Kit', partNo:'PT-SUSP-6806', brand:'TRW', price:5260, mrp:6825, img:'p_susp_29.jpg', type:'Genuine', fitment:'Mahindra Scorpio-N', rating:4.6, reviews:413, stock:true, badge:'' },
  { id:'p_susp_30', cat:'susp', name:'Meyle Rear Air Suspension Spring', partNo:'PT-SUSP-5363', brand:'Meyle', price:2232, mrp:2467, img:'p_susp_30.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.2, reviews:562, stock:true, badge:'Hot' },
  { id:'p_filter_31', cat:'filter', name:'Mann Premium Oil Filter', partNo:'PT-FILTER-3492', brand:'Mann', price:1082, mrp:2374, img:'p_filter_31.jpg', type:'Genuine', fitment:'All Maruti Petrol Cars', rating:4.2, reviews:41, stock:true, badge:'Best Seller' },
  { id:'p_filter_32', cat:'filter', name:'Bosch Engine Air Filter', partNo:'PT-FILTER-6756', brand:'Bosch', price:532, mrp:1635, img:'p_filter_32.webp', type:'Aftermarket', fitment:'Hyundai i20 / Verna 1.5', rating:4.8, reviews:352, stock:true, badge:'New' },
  { id:'p_filter_33', cat:'filter', name:'Mahle Cabin/AC Pollen Filter', partNo:'PT-FILTER-4505', brand:'Mahle', price:4939, mrp:6671, img:'p_filter_33.webp', type:'Genuine', fitment:'Honda City / Amaze', rating:5.0, reviews:550, stock:true, badge:'' },
  { id:'p_filter_34', cat:'filter', name:'K&N Inline Fuel Filter', partNo:'PT-FILTER-4238', brand:'K&N', price:4198, mrp:4978, img:'p_filter_34.jpg', type:'Aftermarket', fitment:'Toyota Innova / Fortuner Diesel', rating:4.3, reviews:102, stock:true, badge:'' },
  { id:'p_filter_35', cat:'filter', name:'Fram ATF Transmission Filter', partNo:'PT-FILTER-8898', brand:'Fram', price:6604, mrp:8564, img:'p_filter_35.jpg', type:'Genuine', fitment:'VW Tiguan / Skoda Kodiaq', rating:4.5, reviews:487, stock:true, badge:'Premium' },
  { id:'p_filter_36', cat:'filter', name:'Purolator Diesel Particulate Filter', partNo:'PT-FILTER-6227', brand:'Purolator', price:6189, mrp:6690, img:'p_filter_36.jpg', type:'Aftermarket', fitment:'Tata Safari Diesel', rating:4.3, reviews:561, stock:true, badge:'' },
  { id:'p_filter_37', cat:'filter', name:'Wix High-Flow Air Intake Filter', partNo:'PT-FILTER-8888', brand:'Wix', price:4989, mrp:6849, img:'p_filter_37.jpg', type:'Genuine', fitment:'Mahindra XUV700 Diesel', rating:4.5, reviews:543, stock:true, badge:'Best Seller' },
  { id:'p_filter_38', cat:'filter', name:'Hengst PCV Breather Valve', partNo:'PT-FILTER-1931', brand:'Hengst', price:5866, mrp:6082, img:'p_filter_38.jpg', type:'Aftermarket', fitment:'Universal Petrol', rating:4.3, reviews:532, stock:true, badge:'New' },
  { id:'p_filter_39', cat:'filter', name:'UFI Crankcase Breather Filter', partNo:'PT-FILTER-7378', brand:'UFI', price:2752, mrp:4272, img:'p_filter_39.jpg', type:'Genuine', fitment:'All Diesel Cars', rating:5.0, reviews:309, stock:true, badge:'' },
  { id:'p_filter_40', cat:'filter', name:'BMC Oil Catch Can Kit', partNo:'PT-FILTER-9281', brand:'BMC', price:1266, mrp:3690, img:'p_filter_40.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.4, reviews:124, stock:true, badge:'Hot' },
  { id:'p_light_41', cat:'light', name:'Osram Full LED Headlight Assembly', partNo:'PT-LIGHT-2146', brand:'Osram', price:4833, mrp:7241, img:'p_light_41.jpg', type:'Genuine', fitment:'Mahindra XUV300', rating:4.5, reviews:131, stock:true, badge:'Best Seller' },
  { id:'p_light_42', cat:'light', name:'Philips Projector Fog Lamp Kit', partNo:'PT-LIGHT-6276', brand:'Philips', price:951, mrp:2116, img:'p_light_42.jpg', type:'Aftermarket', fitment:'Universal H4 Fit', rating:4.9, reviews:414, stock:true, badge:'New' },
  { id:'p_light_43', cat:'light', name:'Hella LED Tail Lamp Assembly', partNo:'PT-LIGHT-6536', brand:'Hella', price:3720, mrp:5012, img:'p_light_43.webp', type:'Genuine', fitment:'Maruti Swift 2018+', rating:4.7, reviews:66, stock:true, badge:'' },
  { id:'p_light_44', cat:'light', name:'Lumax HID Xenon Bulb Kit (D2S)', partNo:'PT-LIGHT-3909', brand:'Lumax', price:3211, mrp:4097, img:'p_light_44.webp', type:'Aftermarket', fitment:'Universal D2S HID', rating:4.2, reviews:367, stock:true, badge:'' },
  { id:'p_light_45', cat:'light', name:'PIAA LED Turn Signal Indicators', partNo:'PT-LIGHT-6777', brand:'PIAA', price:7432, mrp:7602, img:'p_light_45.jpg', type:'Genuine', fitment:'Hyundai Creta / Venue', rating:4.8, reviews:268, stock:true, badge:'Premium' },
  { id:'p_light_46', cat:'light', name:'Sylvania Interior Dome Light LED', partNo:'PT-LIGHT-3557', brand:'Sylvania', price:7088, mrp:7671, img:'p_light_46.jpg', type:'Aftermarket', fitment:'Universal Interior', rating:4.7, reviews:39, stock:true, badge:'' },
  { id:'p_light_47', cat:'light', name:'Narva H4 Hi/Lo Halogen Bulb', partNo:'PT-LIGHT-8678', brand:'Narva', price:1894, mrp:2637, img:'p_light_47.jpg', type:'Genuine', fitment:'Universal H4 Fit', rating:4.7, reviews:297, stock:true, badge:'Best Seller' },
  { id:'p_light_48', cat:'light', name:'GE Lighting Daytime Running Light Strip', partNo:'PT-LIGHT-5040', brand:'GE Lighting', price:1800, mrp:2137, img:'p_light_48.jpg', type:'Aftermarket', fitment:'Universal 12V Strip', rating:4.3, reviews:96, stock:true, badge:'New' },
  { id:'p_light_49', cat:'light', name:'Valeo License Plate Light', partNo:'PT-LIGHT-7750', brand:'Valeo', price:4041, mrp:5154, img:'p_light_49.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.7, reviews:398, stock:false, badge:'' },
  { id:'p_light_50', cat:'light', name:'Depo 3rd Brake Light LED', partNo:'PT-LIGHT-4334', brand:'Depo', price:6965, mrp:8331, img:'p_light_50.jpg', type:'Aftermarket', fitment:'Universal LED', rating:4.8, reviews:338, stock:true, badge:'Hot' },
  { id:'p_elec_51', cat:'elec', name:'Bosch Alternator 65A Reman', partNo:'PT-ELEC-7288', brand:'Bosch', price:2542, mrp:4672, img:'p_elec_51.jpg', type:'Genuine', fitment:'Hyundai Creta / Verna Diesel', rating:4.2, reviews:74, stock:true, badge:'Best Seller' },
  { id:'p_elec_52', cat:'elec', name:'Denso Starter Motor Assembly', partNo:'PT-ELEC-9655', brand:'Denso', price:6983, mrp:8370, img:'p_elec_52.jpg', type:'Aftermarket', fitment:'Maruti Alto / WagonR', rating:4.3, reviews:209, stock:true, badge:'New' },
  { id:'p_elec_53', cat:'elec', name:'Lucas Ignition Coil Pack', partNo:'PT-ELEC-1584', brand:'Lucas', price:6718, mrp:9079, img:'p_elec_53.png', type:'Genuine', fitment:'Universal 4-Cyl Petrol', rating:4.5, reviews:128, stock:true, badge:'' },
  { id:'p_elec_54', cat:'elec', name:'Valeo O2 Lambda Oxygen Sensor', partNo:'PT-ELEC-6134', brand:'Valeo', price:7354, mrp:8725, img:'p_elec_54_prev.jpg', type:'Aftermarket', fitment:'Toyota Fortuner / Innova', rating:4.3, reviews:544, stock:true, badge:'' },
  { id:'p_elec_55', cat:'elec', name:'Hella Mass Air Flow (MAF) Sensor', partNo:'PT-ELEC-7689', brand:'Hella', price:1068, mrp:2521, img:'p_elec_55.jpg', type:'Genuine', fitment:'Maruti Suzuki Swift', rating:4.5, reviews:377, stock:true, badge:'Premium' },
  { id:'p_elec_56', cat:'elec', name:'Minda Power Window Regulator', partNo:'PT-ELEC-9121', brand:'Minda', price:4461, mrp:6549, img:'p_elec_56.png', type:'Aftermarket', fitment:'Honda City 5th Gen', rating:4.9, reviews:229, stock:false, badge:'' },
  { id:'p_elec_57', cat:'elec', name:'Hitachi Windshield Wiper Motor', partNo:'PT-ELEC-1842', brand:'Hitachi', price:5689, mrp:7405, img:'p_elec_57.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.9, reviews:394, stock:true, badge:'Best Seller' },
  { id:'p_elec_58', cat:'elec', name:'Mitsubishi Dual-Tone Loud Horn', partNo:'PT-ELEC-5094', brand:'Mitsubishi', price:2947, mrp:4307, img:'car_electricals_category_1778327286059.jpg', type:'Aftermarket', fitment:'Universal 12V', rating:4.4, reviews:412, stock:true, badge:'New' },
  { id:'p_elec_59', cat:'elec', name:'Magneti Marelli Battery Terminal Clamp Set', partNo:'PT-ELEC-6708', brand:'Magneti Marelli', price:3123, mrp:3679, img:'p_elec_59.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.8, reviews:319, stock:true, badge:'' },
  { id:'p_elec_60', cat:'elec', name:'Delphi Blade Fuse Assortment Kit', partNo:'PT-ELEC-1861', brand:'Delphi', price:7241, mrp:8744, img:'p_elec_60.jpg', type:'Aftermarket', fitment:'Universal Blade Type', rating:4.6, reviews:299, stock:true, badge:'Hot' },
  { id:'p_trans_61', cat:'trans', name:'LUK CV Joint Drive Shaft', partNo:'PT-TRANS-4111', brand:'LUK', price:3436, mrp:5906, img:'p_trans_61.jpg', type:'Genuine', fitment:'VW Polo / Vento', rating:4.9, reviews:459, stock:true, badge:'Best Seller' },
  { id:'p_trans_62', cat:'trans', name:'Sachs Timing Belt & Pulley Kit', partNo:'PT-TRANS-3454', brand:'Sachs', price:5568, mrp:7756, img:'p_trans_62.jpg', type:'Aftermarket', fitment:'Tata Tiago / Tigor', rating:4.9, reviews:291, stock:true, badge:'New' },
  { id:'p_trans_63', cat:'trans', name:'Valeo Transmission Fluid 1L', partNo:'PT-TRANS-9669', brand:'Valeo', price:4942, mrp:5682, img:'p_trans_63.jpg', type:'Genuine', fitment:'Universal ATF', rating:4.8, reviews:232, stock:true, badge:'' },
  { id:'p_trans_64', cat:'trans', name:'Exedy Synchromesh Gear Ring', partNo:'PT-TRANS-3192', brand:'Exedy', price:2224, mrp:4383, img:'p_trans_64.jpg', type:'Aftermarket', fitment:'Universal Manual Gearbox', rating:4.2, reviews:108, stock:true, badge:'' },
  { id:'p_trans_65', cat:'trans', name:'Aisin Rear Differential Bearing', partNo:'PT-TRANS-1834', brand:'Aisin', price:6531, mrp:6791, img:'p_trans_65.jpg', type:'Genuine', fitment:'Toyota Innova / Fortuner', rating:4.7, reviews:265, stock:true, badge:'Premium' },
  { id:'p_trans_66', cat:'trans', name:'ZF Half-Shaft Axle Assembly', partNo:'PT-TRANS-8841', brand:'ZF', price:7373, mrp:8694, img:'p_trans_66.jpg', type:'Aftermarket', fitment:'Hyundai Creta / Tucson', rating:4.7, reviews:313, stock:true, badge:'' },
  { id:'p_trans_67', cat:'trans', name:'BorgWarner Transfer Case Chain Kit', partNo:'PT-TRANS-2310', brand:'BorgWarner', price:6490, mrp:8811, img:'p_trans_67.jpg', type:'Genuine', fitment:'Mahindra Thar / Scorpio', rating:4.7, reviews:347, stock:true, badge:'Best Seller' },
  { id:'p_trans_68', cat:'trans', name:'Jatco Manual Gear Knob & Boot', partNo:'PT-TRANS-9027', brand:'Jatco', price:4210, mrp:6340, img:'p_trans_68.webp', type:'Aftermarket', fitment:'Universal 5/6-Speed', rating:4.6, reviews:30, stock:true, badge:'New' },
  { id:'p_trans_69', cat:'trans', name:'Allison Neutral Safety Switch', partNo:'PT-TRANS-2582', brand:'Allison', price:5193, mrp:6058, img:'p_trans_69.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.2, reviews:455, stock:true, badge:'' },
  { id:'p_trans_70', cat:'trans', name:'Tremec HD Torque Converter', partNo:'PT-TRANS-1046', brand:'Tremec', price:1669, mrp:1950, img:'p_trans_70.jpg', type:'Aftermarket', fitment:'Universal Automatic', rating:4.1, reviews:318, stock:true, badge:'Hot' },
  { id:'p_body_71', cat:'body', name:'Automob OEM Front Bumper Protector', partNo:'PT-BODY-4547', brand:'Automob OEM', price:4047, mrp:6234, img:'p_body_71.jpg', type:'Genuine', fitment:'Maruti Swift / Dzire', rating:4.4, reviews:392, stock:true, badge:'Best Seller' },
  { id:'p_body_72', cat:'body', name:'Genuine Electric Folding Side Mirror', partNo:'PT-BODY-5563', brand:'Genuine', price:2023, mrp:4029, img:'p_body_72.jpg', type:'Aftermarket', fitment:'Honda City 5th Gen', rating:4.5, reviews:527, stock:true, badge:'New' },
  { id:'p_body_73', cat:'body', name:'Depo Fender Splash Guard Liner', partNo:'PT-BODY-8907', brand:'Depo', price:4329, mrp:5258, img:'p_body_73.webp', type:'Genuine', fitment:'Universal Fit', rating:4.8, reviews:247, stock:true, badge:'' },
  { id:'p_body_74', cat:'body', name:'TYC Hood Gas Strut', partNo:'PT-BODY-9764', brand:'TYC', price:1990, mrp:4377, img:'p_body_74.jpg', type:'Aftermarket', fitment:'Universal Strut', rating:4.3, reviews:352, stock:true, badge:'' },
  { id:'p_body_75', cat:'body', name:'Sherman Exterior Door Handle', partNo:'PT-BODY-7312', brand:'Sherman', price:7061, mrp:9136, img:'p_body_75.jpg', type:'Genuine', fitment:'Universal Pull Type', rating:4.4, reviews:567, stock:true, badge:'Premium' },
  { id:'p_body_76', cat:'body', name:'Replace Honeycomb Radiator Grille', partNo:'PT-BODY-2842', brand:'Replace', price:5940, mrp:7262, img:'p_body_76.jpg', type:'Aftermarket', fitment:'Universal Mesh', rating:4.6, reviews:526, stock:true, badge:'' },
  { id:'p_body_77', cat:'body', name:'Kool Vue Rear Tailgate Strut', partNo:'PT-BODY-5917', brand:'Kool Vue', price:5921, mrp:8273, img:'p_body_77.jpg', type:'Genuine', fitment:'Universal Hatch', rating:4.7, reviews:180, stock:true, badge:'Best Seller' },
  { id:'p_body_78', cat:'body', name:'Dorman Rear Mud Guard Flaps', partNo:'PT-BODY-6226', brand:'Dorman', price:2090, mrp:4445, img:'p_body_78.jpg', type:'Aftermarket', fitment:'Universal Rubber', rating:4.7, reviews:535, stock:true, badge:'New' },
  { id:'p_body_79', cat:'body', name:'Omix Aluminum Roof Rails', partNo:'PT-BODY-2704', brand:'Omix', price:2068, mrp:2862, img:'p_body_79.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.9, reviews:489, stock:true, badge:'' },
  { id:'p_body_80', cat:'body', name:'Crown Engine Skid Under Cover', partNo:'PT-BODY-1401', brand:'Crown', price:2102, mrp:3801, img:'p_body_80.jpg', type:'Aftermarket', fitment:'Universal Underbody', rating:4.3, reviews:449, stock:true, badge:'Hot' },
  { id:'p_wiper_81', cat:'wiper', name:'Bosch AeroTwin Flat Wiper Set', partNo:'PT-WIPER-9252', brand:'Bosch', price:3336, mrp:5324, img:'p_wiper_81.jpg', type:'Genuine', fitment:'26"/16" Universal', rating:4.9, reviews:415, stock:true, badge:'Best Seller' },
  { id:'p_wiper_82', cat:'wiper', name:'Valeo Rear Window Wiper Blade', partNo:'PT-WIPER-3904', brand:'Valeo', price:1855, mrp:4060, img:'p_wiper_82.webp', type:'Aftermarket', fitment:'Hyundai Creta / Venue', rating:4.6, reviews:281, stock:true, badge:'New' },
  { id:'p_wiper_83', cat:'wiper', name:'Michelin Silicone Beam Wiper Set', partNo:'PT-WIPER-7475', brand:'Michelin', price:3249, mrp:4629, img:'p_wiper_83.jpg', type:'Genuine', fitment:'Universal 24"/16"', rating:4.8, reviews:255, stock:true, badge:'' },
  { id:'p_wiper_84', cat:'wiper', name:'Rain-X Hybrid Winter Wiper', partNo:'PT-WIPER-9336', brand:'Rain-X', price:507, mrp:2328, img:'p_wiper_84.webp', type:'Aftermarket', fitment:'Universal Winter', rating:4.5, reviews:343, stock:true, badge:'' },
  { id:'p_wiper_85', cat:'wiper', name:'Trico Windshield Washer Fluid 5L', partNo:'PT-WIPER-8725', brand:'Trico', price:6586, mrp:8864, img:'p_wiper_85.jpg', type:'Genuine', fitment:'Universal 5L', rating:4.1, reviews:475, stock:true, badge:'Premium' },
  { id:'p_wiper_86', cat:'wiper', name:'Denso Wiper Arm Assembly', partNo:'PT-WIPER-3740', brand:'Denso', price:5777, mrp:6088, img:'p_wiper_86.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.5, reviews:398, stock:true, badge:'' },
  { id:'p_wiper_87', cat:'wiper', name:'Hella Washer Pump Motor', partNo:'PT-WIPER-2753', brand:'Hella', price:6283, mrp:7101, img:'p_wiper_87.jpg', type:'Genuine', fitment:'Universal 12V', rating:4.6, reviews:96, stock:true, badge:'Best Seller' },
  { id:'p_wiper_88', cat:'wiper', name:'Syndicate Wiper Transmission Linkage', partNo:'PT-WIPER-7836', brand:'Syndicate', price:2261, mrp:4290, img:'p_wiper_88.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.9, reviews:582, stock:true, badge:'New' },
  { id:'p_wiper_89', cat:'wiper', name:'NWB Graphite Flat Wiper Blade', partNo:'PT-WIPER-5902', brand:'NWB', price:6299, mrp:8073, img:'p_wiper_89.jpg', type:'Genuine', fitment:'Universal 24"', rating:4.3, reviews:178, stock:true, badge:'' },
  { id:'p_wiper_90', cat:'wiper', name:'PIAA Heavy-Duty All-Season Wiper', partNo:'PT-WIPER-7876', brand:'PIAA', price:6488, mrp:8887, img:'p_wiper_90.jpg', type:'Aftermarket', fitment:'Universal Heavy Duty', rating:4.6, reviews:544, stock:true, badge:'Hot' },
  { id:'p_battery_91', cat:'battery', name:'Exide MF 35Ah Hatchback Battery', partNo:'PT-BATTERY-9289', brand:'Exide', price:2957, mrp:4856, img:'p_battery_91.png', type:'Genuine', fitment:'Small Hatchbacks', rating:4.6, reviews:51, stock:true, badge:'Best Seller' },
  { id:'p_battery_92', cat:'battery', name:'Amaron Pro 44Ah Sedan Battery', partNo:'PT-BATTERY-4763', brand:'Amaron', price:3752, mrp:5100, img:'p_battery_92.png', type:'Aftermarket', fitment:'Mid Sedans & SUVs', rating:4.2, reviews:162, stock:true, badge:'New' },
  { id:'p_battery_93', cat:'battery', name:'Bosch AGM Start-Stop 60Ah Battery', partNo:'PT-BATTERY-7277', brand:'Bosch', price:7434, mrp:9113, img:'p_battery_93.webp', type:'Genuine', fitment:'Start-Stop Vehicles', rating:4.9, reviews:301, stock:true, badge:'' },
  { id:'p_battery_94', cat:'battery', name:'Varta Deep Cycle 75Ah Battery', partNo:'PT-BATTERY-1989', brand:'Varta', price:2033, mrp:2340, img:'p_battery_94.jpg', type:'Aftermarket', fitment:'Deep Cycle Off-Road', rating:4.1, reviews:537, stock:true, badge:'' },
  { id:'p_battery_95', cat:'battery', name:'Optima 12V Motorcycle Battery', partNo:'PT-BATTERY-8059', brand:'Optima', price:680, mrp:1012, img:'p_battery_95.jpg', type:'Genuine', fitment:'All Motorcycles', rating:4.3, reviews:180, stock:true, badge:'Premium' },
  { id:'p_battery_96', cat:'battery', name:'Yuasa 12V Lithium Jump Starter', partNo:'PT-BATTERY-6163', brand:'Yuasa', price:1446, mrp:1710, img:'p_battery_96.jpg', type:'Aftermarket', fitment:'Universal 12V Jump', rating:4.3, reviews:251, stock:true, badge:'' },
  { id:'p_battery_97', cat:'battery', name:'ACDelco Smart Battery Charger 12V', partNo:'PT-BATTERY-6194', brand:'ACDelco', price:6440, mrp:8577, img:'p_battery_97.jpg', type:'Genuine', fitment:'Universal 12V Cars', rating:4.4, reviews:159, stock:true, badge:'Best Seller' },
  { id:'p_battery_98', cat:'battery', name:'DieHard Battery Float Tender', partNo:'PT-BATTERY-8456', brand:'DieHard', price:2674, mrp:2886, img:'p_battery_98.jpg', type:'Aftermarket', fitment:'Universal Maintainer', rating:5.0, reviews:465, stock:true, badge:'New' },
  { id:'p_battery_99', cat:'battery', name:'Duralast 150Ah Inverter Battery', partNo:'PT-BATTERY-8518', brand:'Duralast', price:4041, mrp:4637, img:'p_battery_99.jpg', type:'Genuine', fitment:'Home Inverter', rating:4.4, reviews:354, stock:false, badge:'' },
  { id:'p_battery_100', cat:'battery', name:'Odyssey Heavy Duty 100Ah Truck Battery', partNo:'PT-BATTERY-6353', brand:'Odyssey', price:1820, mrp:2043, img:'car_battery_product_1778327386793.jpg', type:'Aftermarket', fitment:'Heavy Trucks & MUVs', rating:4.9, reviews:594, stock:true, badge:'Hot' },
  { id:'p_clutch_101', cat:'clutch', name:'LUK 3-Piece Clutch Kit (OE)', partNo:'PT-CLUTCH-7315', brand:'LUK', price:7294, mrp:9732, img:'car_clutch_kit_product_1778327402731.jpg', type:'Genuine', fitment:'Tata Tiago / Tigor / Altroz', rating:4.6, reviews:586, stock:true, badge:'Best Seller' },
  { id:'p_clutch_102', cat:'clutch', name:'Sachs Heavy Duty Sport Clutch', partNo:'PT-CLUTCH-5022', brand:'Sachs', price:2501, mrp:3734, img:'engine_head_gasket.jpg', type:'Aftermarket', fitment:'Maruti Swift / Baleno', rating:4.5, reviews:297, stock:true, badge:'New' },
  { id:'p_clutch_103', cat:'clutch', name:'Valeo Dual Mass Flywheel', partNo:'PT-CLUTCH-6651', brand:'Valeo', price:2722, mrp:4305, img:'p_clutch_103.jpg', type:'Genuine', fitment:'Toyota Innova Diesel', rating:4.6, reviews:57, stock:true, badge:'' },
  { id:'p_clutch_104', cat:'clutch', name:'Exedy Clutch Slave Cylinder', partNo:'PT-CLUTCH-4908', brand:'Exedy', price:3545, mrp:5931, img:'p_clutch_104.webp', type:'Aftermarket', fitment:'Hyundai i20 / Verna', rating:4.7, reviews:103, stock:true, badge:'' },
  { id:'p_clutch_105', cat:'clutch', name:'Aisin Clutch Master Cylinder', partNo:'PT-CLUTCH-3747', brand:'Aisin', price:4276, mrp:5967, img:'p_clutch_105.webp', type:'Genuine', fitment:'Honda City / Amaze', rating:4.5, reviews:144, stock:true, badge:'Premium' },
  { id:'p_clutch_106', cat:'clutch', name:'Mcleod Performance HD Clutch Plate', partNo:'PT-CLUTCH-7073', brand:'Mcleod', price:5774, mrp:8054, img:'p_clutch_106.jpg', type:'Aftermarket', fitment:'Maruti Vitara Brezza', rating:5.0, reviews:522, stock:true, badge:'' },
  { id:'p_clutch_107', cat:'clutch', name:'Centerforce Clutch Release Bearing', partNo:'PT-CLUTCH-3627', brand:'Centerforce', price:4357, mrp:5590, img:'p_clutch_107.jpg', type:'Genuine', fitment:'Universal Fit', rating:5.0, reviews:240, stock:true, badge:'Best Seller' },
  { id:'p_clutch_108', cat:'clutch', name:'Spec Braided Clutch Cable', partNo:'PT-CLUTCH-3561', brand:'Spec', price:2726, mrp:4317, img:'p_clutch_108.jpg', type:'Aftermarket', fitment:'Universal Fit', rating:4.3, reviews:252, stock:true, badge:'New' },
  { id:'p_clutch_109', cat:'clutch', name:'ACT Pilot Shaft Bearing', partNo:'PT-CLUTCH-3632', brand:'ACT', price:3180, mrp:5288, img:'car_clutch_kit_product_1778327402731.jpg', type:'Genuine', fitment:'Universal Fit', rating:4.3, reviews:125, stock:true, badge:'' },
  { id:'p_clutch_110', cat:'clutch', name:'Clutch Masters Clutch Spline Alignment Tool', partNo:'PT-CLUTCH-1170', brand:'Clutch Masters', price:5145, mrp:5940, img:'p_clutch_110.png', type:'Aftermarket', fitment:'Universal Fit', rating:5.0, reviews:362, stock:true, badge:'Hot' },
  { id:'p_wheel_111', cat:'wheel', name:'BBS 16" Diamond-Cut Alloy Wheel', partNo:'PT-WHEEL-8111', brand:'BBS', price:6487, mrp:6852, img:'p_wheel_111.jpg', type:'Genuine', fitment:'PCD 4×100 / ET35', rating:4.6, reviews:122, stock:true, badge:'Best Seller' },
  { id:'p_wheel_112', cat:'wheel', name:'Enkei 15" Hyper Silver Alloy (x4)', partNo:'PT-WHEEL-9999', brand:'Enkei', price:3949, mrp:5227, img:'p_wheel_112.jpg', type:'Aftermarket', fitment:'PCD 4×100 / ET40', rating:4.7, reviews:255, stock:true, badge:'New' },
  { id:'p_wheel_113', cat:'wheel', name:'OZ Racing 17" Matte Black Alloy Wheel', partNo:'PT-WHEEL-5997', brand:'OZ Racing', price:1204, mrp:1874, img:'p_wheel_113.jpg', type:'Genuine', fitment:'PCD 5×114 / ET45', rating:4.9, reviews:32, stock:true, badge:'' },
  { id:'p_wheel_114', cat:'wheel', name:'Momo 14" Steel Spare Wheel', partNo:'PT-WHEEL-2335', brand:'Momo', price:5918, mrp:7665, img:'p_wheel_114.jpg', type:'Aftermarket', fitment:'Universal Steel', rating:4.3, reviews:401, stock:true, badge:'' },
  { id:'p_wheel_115', cat:'wheel', name:'Sparco 60-Piece Lug Nut Kit', partNo:'PT-WHEEL-9712', brand:'Sparco', price:706, mrp:2047, img:'p_wheel_115.jpg', type:'Genuine', fitment:'Universal 12×1.25', rating:4.4, reviews:334, stock:true, badge:'Premium' },
  { id:'p_wheel_116', cat:'wheel', name:'Vossen Hub-Centric Bore Ring Set', partNo:'PT-WHEEL-5494', brand:'Vossen', price:2308, mrp:3524, img:'p_wheel_116.png', type:'Aftermarket', fitment:'Universal 60.1mm Bore', rating:4.4, reviews:598, stock:true, badge:'' },
  { id:'p_wheel_117', cat:'wheel', name:'HRE Brass Tire Valve Stems (x10)', partNo:'PT-WHEEL-1875', brand:'HRE', price:4862, mrp:5121, img:'p_wheel_117.jpg', type:'Genuine', fitment:'Universal TR413', rating:4.5, reviews:408, stock:true, badge:'Best Seller' },
  { id:'p_wheel_118', cat:'wheel', name:'Volk 20mm Wheel Spacers (Pair)', partNo:'PT-WHEEL-7906', brand:'Volk', price:4710, mrp:6998, img:'car_alloy_wheel_product_1778327419390.jpg', type:'Aftermarket', fitment:'5×112 / ET35', rating:4.2, reviews:100, stock:true, badge:'New' },
  { id:'p_wheel_119', cat:'wheel', name:'Konig Alloy Center Caps Set (x4)', partNo:'PT-WHEEL-7807', brand:'Konig', price:487, mrp:2756, img:'p_wheel_119.jpg', type:'Genuine', fitment:'Universal 4-Stud', rating:4.4, reviews:82, stock:true, badge:'' },
  { id:'p_wheel_120', cat:'wheel', name:'Rotiform 19" Forged Racing Wheel', partNo:'PT-WHEEL-7025', brand:'Rotiform', price:4277, mrp:4492, img:'p_wheel_120.jpg', type:'Aftermarket', fitment:'PCD 5×120 / ET45', rating:4.8, reviews:237, stock:true, badge:'Hot' },
  { id:'p_bike_gear_121', cat:'bike_gear', name:'Alpinestars Full-Face Riding Helmet', partNo:'PT-BIKEGEAR-2132', brand:'Alpinestars', price:3294, mrp:3908, img:'bike_helmet.jpg', type:'Genuine', fitment:'Universal XS-XXL', rating:4.3, reviews:38, stock:true, badge:'Best Seller' },
  { id:'p_bike_gear_122', cat:'bike_gear', name:'Dainese CE Level 2 Riding Gloves', partNo:'PT-BIKEGEAR-8320', brand:'Dainese', price:5825, mrp:6832, img:'p_bike_gear_122.jpg', type:'Aftermarket', fitment:'Universal S-XL', rating:4.9, reviews:294, stock:true, badge:'New' },
  { id:'p_bike_gear_123', cat:'bike_gear', name:'Fox Armored Riding Jacket', partNo:'PT-BIKEGEAR-6030', brand:'Fox', price:2509, mrp:3361, img:'p_bike_gear_123.jpg', type:'Genuine', fitment:'Universal M-XL', rating:4.7, reviews:107, stock:true, badge:'' },
  { id:'p_bike_gear_124', cat:'bike_gear', name:'Shoei Hard Shell Knee Guards', partNo:'PT-BIKEGEAR-4675', brand:'Shoei', price:1972, mrp:2996, img:'p_bike_gear_124.jpg', type:'Aftermarket', fitment:'Universal', rating:4.4, reviews:421, stock:true, badge:'' },
  { id:'p_bike_gear_125', cat:'bike_gear', name:'Arai Waterproof Riding Boots', partNo:'PT-BIKEGEAR-1641', brand:'Arai', price:4929, mrp:6629, img:'p_bike_gear_125.jpg', type:'Genuine', fitment:'EU Size 40-46', rating:4.7, reviews:343, stock:true, badge:'Premium' },
  { id:'p_bike_gear_126', cat:'bike_gear', name:'AGV Thermal Balaclava Inner Mask', partNo:'PT-BIKEGEAR-1186', brand:'AGV', price:2549, mrp:4438, img:'p_bike_gear_126.jpg', type:'Aftermarket', fitment:'Universal One Size', rating:4.8, reviews:155, stock:true, badge:'' },
  { id:'p_bike_gear_127', cat:'bike_gear', name:'Bell Expandable Tank Top Bag', partNo:'PT-BIKEGEAR-6512', brand:'Bell', price:7323, mrp:8678, img:'p_bike_gear_127.webp', type:'Genuine', fitment:'Universal Fit', rating:4.2, reviews:192, stock:true, badge:'Best Seller' },
  { id:'p_bike_gear_128', cat:'bike_gear', name:'HJC Bluetooth Helmet Intercom', partNo:'PT-BIKEGEAR-3583', brand:'HJC', price:4909, mrp:6293, img:'p_bike_gear_128.jpg', type:'Aftermarket', fitment:'Universal BT 4.1', rating:4.2, reviews:560, stock:true, badge:'New' },
  { id:'p_bike_gear_129', cat:'bike_gear', name:'Klim 2-Piece Rain Riding Suit', partNo:'PT-BIKEGEAR-1300', brand:'Klim', price:2183, mrp:3426, img:'bike_gloves.jpg', type:'Genuine', fitment:'Universal Jacket+Pants', rating:4.6, reviews:289, stock:true, badge:'' },
  { id:'p_bike_gear_130', cat:'bike_gear', name:'Revit Hi-Viz Reflective Safety Vest', partNo:'PT-BIKEGEAR-4898', brand:'Revit', price:7113, mrp:8481, img:'p_bike_gear_130.jpg', type:'Aftermarket', fitment:'Universal High-Vis', rating:4.3, reviews:562, stock:false, badge:'Hot' },
  { id:'p_bike_care_131', cat:'bike_care', name:'Motul All-Weather Chain Lube Spray', partNo:'PT-BIKECARE-4996', brand:'Motul', price:3509, mrp:3705, img:'p_bike_care_131.jpg', type:'Genuine', fitment:'All Motorcycles', rating:4.2, reviews:417, stock:true, badge:'Best Seller' },
  { id:'p_bike_care_132', cat:'bike_care', name:'Muc-Off Chain Degreaser & Cleaner', partNo:'PT-BIKECARE-9505', brand:'Muc-Off', price:1136, mrp:1847, img:'p_bike_care_132.webp', type:'Aftermarket', fitment:'All Chain Types', rating:4.5, reviews:253, stock:true, badge:'New' },
  { id:'p_bike_care_133', cat:'bike_care', name:'WD-40 Foaming Wash Shampoo 1L', partNo:'PT-BIKECARE-4386', brand:'WD-40', price:6972, mrp:7435, img:'p_bike_care_133.jpg', type:'Genuine', fitment:'All Motorcycles', rating:4.4, reviews:468, stock:true, badge:'' },
  { id:'p_bike_care_134', cat:'bike_care', name:'Maxima Helmet Visor Anti-Fog Spray', partNo:'PT-BIKECARE-5955', brand:'Maxima', price:1670, mrp:2454, img:'p_bike_care_134.jpg', type:'Aftermarket', fitment:'All Visors & Helmets', rating:4.4, reviews:496, stock:false, badge:'' },
  { id:'p_bike_care_135', cat:'bike_care', name:'Bel-Ray 10W40 Mineral Engine Oil 1L', partNo:'PT-BIKECARE-8971', brand:'Bel-Ray', price:3771, mrp:4600, img:'bike_chain_lube.jpg', type:'Genuine', fitment:'All 4-Stroke Engines', rating:4.6, reviews:383, stock:true, badge:'Premium' },
  { id:'p_bike_care_136', cat:'bike_care', name:'Castrol Matte Finish Polish Spray', partNo:'PT-BIKECARE-5494', brand:'Castrol', price:7390, mrp:8578, img:'p_bike_care_136.png', type:'Aftermarket', fitment:'All Matte Surfaces', rating:4.5, reviews:464, stock:true, badge:'' },
  { id:'p_bike_care_137', cat:'bike_care', name:'Liqui Moly Rust & Corrosion Remover', partNo:'PT-BIKECARE-8765', brand:'Liqui Moly', price:6472, mrp:8329, img:'p_bike_care_137.jpg', type:'Genuine', fitment:'All Metals', rating:5.0, reviews:283, stock:true, badge:'Best Seller' },
  { id:'p_bike_care_138', cat:'bike_care', name:'Meguiars Self-Sealing Tubeless Sealant', partNo:'PT-BIKECARE-7817', brand:'Meguiars', price:4717, mrp:6474, img:'p_bike_care_138.webp', type:'Aftermarket', fitment:'All Tubeless Tires', rating:4.7, reviews:600, stock:true, badge:'New' },
  { id:'p_bike_care_139', cat:'bike_care', name:'Turtle Wax Premium Microfiber Cloth Set', partNo:'PT-BIKECARE-3072', brand:'Turtle Wax', price:2877, mrp:3257, img:'p_bike_care_139.png', type:'Genuine', fitment:'Universal', rating:4.2, reviews:592, stock:true, badge:'' },
  { id:'p_bike_care_140', cat:'bike_care', name:'Sonax Disc Brake Aerosol Cleaner', partNo:'PT-BIKECARE-7217', brand:'Sonax', price:2168, mrp:4268, img:'bike_chain_lube.jpg', type:'Aftermarket', fitment:'All Disc Brakes', rating:4.3, reviews:113, stock:true, badge:'Hot' },
  { id:'p_car_acc_141', cat:'car_acc', name:'70mai 4K Dual-Channel Dash Camera', partNo:'PT-CARACC-1003', brand:'70mai', price:5239, mrp:5614, img:'p_car_acc_141.jpg', type:'Genuine', fitment:'Universal Dash Mount', rating:4.7, reviews:331, stock:true, badge:'Best Seller' },
  { id:'p_car_acc_142', cat:'car_acc', name:'Viofo Custom-Fit Leather Seat Covers', partNo:'PT-CARACC-1597', brand:'Viofo', price:5723, mrp:8131, img:'p_car_acc_142.jpg', type:'Aftermarket', fitment:'Custom Fit – Specify Model', rating:4.5, reviews:515, stock:true, badge:'New' },
  { id:'p_car_acc_143', cat:'car_acc', name:'Garmin Luxury Woody Car Perfume', partNo:'PT-CARACC-7203', brand:'Garmin', price:5896, mrp:6405, img:'p_car_acc_143.jpg', type:'Genuine', fitment:'Universal Air Freshener', rating:4.6, reviews:50, stock:true, badge:'' },
  { id:'p_car_acc_144', cat:'car_acc', name:'Spigen Sporty Steering Wheel Cover', partNo:'PT-CARACC-1877', brand:'Spigen', price:5420, mrp:7818, img:'p_car_acc_144.jpg', type:'Aftermarket', fitment:'Diameter 37-38cm', rating:4.6, reviews:392, stock:true, badge:'' },
  { id:'p_car_acc_145', cat:'car_acc', name:'Baseus Cordless Car Vacuum Cleaner', partNo:'PT-CARACC-3824', brand:'Baseus', price:5807, mrp:6516, img:'p_car_acc_145.jpg', type:'Genuine', fitment:'Universal 12V / USB', rating:4.6, reviews:153, stock:true, badge:'Premium' },
  { id:'p_car_acc_146', cat:'car_acc', name:'AmbiPur Digital Tire Inflator Pump', partNo:'PT-CARACC-5275', brand:'AmbiPur', price:7037, mrp:8039, img:'p_car_acc_146.jpg', type:'Aftermarket', fitment:'Universal 12V', rating:4.9, reviews:290, stock:true, badge:'' },
  { id:'p_car_acc_147', cat:'car_acc', name:'Godrej Universal Magnetic Phone Mount', partNo:'PT-CARACC-5845', brand:'Godrej', price:4517, mrp:6339, img:'p_car_acc_147.jpg', type:'Genuine', fitment:'Universal Magnetic', rating:4.3, reviews:324, stock:true, badge:'Best Seller' },
  { id:'p_car_acc_148', cat:'car_acc', name:'3M 7D Custom Floor Mats Set', partNo:'PT-CARACC-4382', brand:'3M', price:2935, mrp:4665, img:'p_car_acc_148.jpg', type:'Aftermarket', fitment:'Universal with Clips', rating:4.5, reviews:589, stock:true, badge:'New' },
  { id:'p_car_acc_149', cat:'car_acc', name:'Armor All Windshield UV Sun Shade', partNo:'PT-CARACC-4244', brand:'Armor All', price:3759, mrp:5444, img:'p_car_acc_149.jpg', type:'Genuine', fitment:'Universal 130×60cm', rating:4.6, reviews:375, stock:true, badge:'' },
  { id:'p_car_acc_150', cat:'car_acc', name:'Michelin Collapsible Trunk Organizer', partNo:'PT-CARACC-1771', brand:'Michelin', price:1591, mrp:2050, img:'p_car_acc_150.jpg', type:'Aftermarket', fitment:'Universal 42L', rating:4.8, reviews:489, stock:true, badge:'Hot' },
];

export const BRANDS = [
  { name:'Maruti Suzuki', slug:'maruti' },{ name:'Hyundai', slug:'hyundai' },
  { name:'Honda', slug:'honda' },{ name:'Toyota', slug:'toyota' },
  { name:'Tata', slug:'tata' },{ name:'Mahindra', slug:'mahindra' },
  { name:'Kia', slug:'kia' },{ name:'MG', slug:'mg' },
  { name:'Royal Enfield', slug:'royal-enfield' },{ name:'Yamaha', slug:'yamaha' },
  { name:'KTM', slug:'ktm' },{ name:'Bajaj', slug:'bajaj' },
];

export const TESTIMONIALS = [
  { name:'Rajesh Kumar', city:'Delhi', text:'Got genuine Brembo pads delivered in 2 days. Excellent quality. Will order again!', rating:5, car:'Hyundai i20' },
  { name:'Priya Sharma', city:'Bangalore', text:'The Bosch wiper blades are perfect. Cleared the windshield like brand new.', rating:5, car:'Honda City' },
  { name:'Amit Patel', city:'Ahmedabad', text:'NGK spark plugs improved mileage noticeably. Fast shipping, great packaging.', rating:4, car:'Maruti Baleno' },
  { name:'Deepa Nair', city:'Chennai', text:'Best prices online. Got Exide battery installed via their tie-up mechanic. 10/10!', rating:5, car:'Toyota Innova' },
  { name:'Suresh Mehta', city:'Mumbai', text:'KYB shocks transformed my ride quality. Easy install and great value for money.', rating:5, car:'Kia Seltos' },
  { name:'Anita Verma', city:'Pune', text:'Ordered a full clutch kit for my Swift. Fitment perfect, genuine LUK parts!', rating:5, car:'Maruti Swift' },
  { id:'p_bike_gear_200', cat:'bike_gear', name:'Vega Crux Half Face Helmet', partNo:'PT-BIKEGEAR-4001', brand:'Vega', price:1150, mrp:1350, img:'p_bike_gear_200.jpg', type:'Genuine', fitment:'Universal M/L', rating:4.5, reviews:852, stock:true, badge:'Best Seller' },
  { id:'p_bike_gear_201', cat:'bike_gear', name:'Studds Thunder Full Face Helmet', partNo:'PT-BIKEGEAR-4002', brand:'Studds', price:1850, mrp:2150, img:'p_bike_gear_201.jpg', type:'Genuine', fitment:'Universal L/XL', rating:4.7, reviews:1245, stock:true, badge:'Hot' },
  { id:'p_bike_gear_202', cat:'bike_gear', name:'SMK Twister Full Face Helmet', partNo:'PT-BIKEGEAR-4003', brand:'SMK', price:4300, mrp:4800, img:'p_bike_gear_202.jpg', type:'Genuine', fitment:'Universal L', rating:4.8, reviews:320, stock:true, badge:'Premium' },
  { id:'p_bike_gear_203', cat:'bike_gear', name:'Royal Enfield Classic Open Face Helmet', partNo:'PT-BIKEGEAR-4004', brand:'Royal Enfield', price:2400, mrp:2700, img:'p_bike_gear_203.jpg', type:'Genuine', fitment:'Universal L', rating:4.6, reviews:412, stock:true, badge:'' },
  { id:'p_bike_gear_204', cat:'bike_gear', name:'Axor Street Batman Graphic Helmet', partNo:'PT-BIKEGEAR-4005', brand:'Axor', price:4999, mrp:5499, img:'p_bike_gear_204.jpg', type:'Genuine', fitment:'Universal M/L', rating:4.9, reviews:521, stock:true, badge:'New' },
];

export const categories = CATEGORIES;
export const products   = PRODUCTS;

export const getProductById       = (id)    => PRODUCTS.find(p => p.id === id);
export const getCategoryById      = (id)    => CATEGORIES.find(c => c.id === id);
export const getProductsByCategory = (catId) => catId ? PRODUCTS.filter(p => p.cat === catId) : PRODUCTS;

export const fmt      = (n) => '₹' + n.toLocaleString('en-IN');
export const discount = (price, mrp) => Math.round(((mrp - price) / mrp) * 100);
